name: dfirtimeline
version: '3.8'

services:
  dfir-opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: dfir-opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /opt/dfir/opensearch/data:/usr/share/opensearch/data
      - /opt/dfir/opensearch/plugins:/usr/share/opensearch/plugins
      - /opt/dfir/opensearch/config:/usr/share/opensearch/config
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
  dfir-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: dfir-dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://dfir-opensearch:9200"]'
    volumes:
      - /opt/dfir/opensearch-dashboards/config:/usr/share/opensearch-dashboards/config
      - /opt/dfir/opensearch-dashboards/data:/usr/share/opensearch-dashboards/data
    ports:
      - 5601:5601 # Dashboards
