name: dfirtimeline

services:
  dfir-opensearch:
    image: opensearchproject/opensearch:3.0.0
    container_name: dfir-opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${INIT_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - openasearch-data:/usr/share/opensearch/data
      - openasearch-plugins:/usr/share/opensearch/plugins
      - openasearch-config:/usr/share/opensearch/config
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
  dfir-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: dfir-dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["https://dfir-opensearch:9200"]'
    volumes:
      - dashboard-config:/usr/share/opensearch-dashboards/config
      - dashboard-data:/usr/share/opensearch-dashboards/data
    ports:
      - 5601:5601 # Dashboards

volumes:
  openasearch-config:
  openasearch-data:
  openasearch-plugins:
  dashboard-config:
  dashboard-data:
