name: Assign Pull Request Creator

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'
      - 'stable'
      - 'release/v*'
      - 'development'

permissions:
  contents: read

jobs:
  assign-assignees:
    permissions:
      issues: write
      pull-requests: write
    uses: dafneb/.github/.github/workflows/pull-request-assignee.yml@73cd59b01daa56d6d1db5d99379cb525f9a448a7
    with:
      assignees: ${{ github.actor }}
    secrets: inherit
